apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: npm
  description: NPM is a tool/service for installing React packages
  annotations:
    backstage.io/techdocs-ref: url:https://www.npmjs.com/
  tags:
    - javascript
    - react
    - docs
  links:
    - url: https://www.npmjs.com/
      title: NPM Official Website
      icon: web
    - url: https://docs.npmjs.com/
      title: NPM Official Documentation
      icon: web

spec:
  type: service
  lifecycle: production
  owner: xoho-tech
  # system: artist-engagement-portal
